name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get PR Diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }} > pr.diff

      - name: Ask Claude to review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          node << 'EOF'
          const fs = require("fs");
          const axios = require("axios");

          const diff = fs.readFileSync("pr.diff", "utf8");

          async function review() {
            const response = await axios.post(
              "https://api.anthropic.com/v1/messages",
              {
                model: "claude-3-5-sonnet-latest",
                max_tokens: 1500,
                messages: [
                  {
                    role: "user",
                    content: `You are a senior engineer. Review this PR diff and provide structured feedback:\n\n${diff}`
                  }
                ]
              },
              {
                headers: {
                  "x-api-key": process.env.ANTHROPIC_API_KEY,
                  "anthropic-version": "2023-06-01",
                  "content-type": "application/json"
                }
              }
            );

            const reviewText = response.data.content[0].text;
            fs.writeFileSync("review.txt", reviewText);
          }

          review();
          EOF

      # 👇 STEP 3 GOES HERE
      - name: Post Claude Review as PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.txt', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "## 🤖 Claude Code Review\n\n" + review
            });
